config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'entries/search/(:content_search)/(:tag_search)', to: 'entries#index', as: 'entries_search'
  resources :entries, :projects
  get 'tags/', to: 'tags#index'
  get 'tags/:tag', to: 'tags#show', as: 'tag'
  root to: "static#landing_page", as: 'landing_page'
  get '/*foo', to: redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :project_entries
  has_many :projects, through: :project_entries
  acts_as_taggable
  pg_search_scope :search_for, against: %i(title description content)
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :project_users
  has_many :users, through: :project_users
  has_many :project_entries
  has_many :entries, through: :project_entries

  def members
    return users << owner
  end

end

app/models/project_entry.rb
class ProjectEntry < ApplicationRecord
  belongs_to :project
  belongs_to :entry

  validates :entry_id, :uniqueness => { :scope => :project_id }
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :user_id, :uniqueness => { :scope => :project_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entries
  has_many :projects, foreign_key: "owner_id"
  validates :email, uniqueness: true

  # The owner_entries query is more complicated than it would otherwise need to be because it needs to maintain
  # a parallel structure to the member_entries query, else they cannot be or'd together
  def owner_entries
    Entry.joins({:projects => :users}).where(:entries => {user_id: id}).distinct(:entries => :id)
  end

  def member_entries
    Entry.joins({:projects => :users}).where(:users => {id: id}).distinct(:entries => :id)
  end

  def accessible_entries
    owner_entries.or(member_entries)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  # GET /entries
  def index
    @entries = [] and return unless current_user
    @entries = current_user.accessible_entries
    unless params[:content_search].blank?
      @entries = Entry.search_for params[:content_search]
    end
    unless params[:tag_search].blank?
      terms = params[:tag_search].split(' ')
      @includes = terms.select do |term|
        term.chr != '-'
      end
      @excludes = terms.select do |term|
        term.chr == '-'
      end.map do |term|
        term[1..-1]
      end
      unless @includes.empty?
        @entries = @entries.tagged_with(@includes)
      end
      unless @excludes.empty?
        @entries = @entries.tagged_with(@excludes, exclude: true) 
      end
    end
  end

  # GET /entries/1
  def show
    authorize_entry(params[:id])
  end

  # GET /entries/new
  def new
    redirect_to entries_path, notice: 'You must be logged in to create an entry.' and return unless current_user
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    authorize_entry(params[:id])
  end

  # POST /entries
  def create
    head :unauthorized and return unless current_user
    @entry = Entry.new(entry_params.merge(user_id: current_user.id))
    if @entry.save
      redirect_to @entry, notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /entries/1
  def update
    authorize_entry(params[:id])
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /entries/1
  def destroy
    @entry = Entry.find(params[:id])
    head :unauthorized and return unless @entry.user == current_user
    @entry.destroy
    redirect_to entries_path, notice: 'Entry was successfully destroyed.'
  end

  private

  def authorize_entry(id)
    @entry = Entry.find(params[:id])
    head :unauthorized and return unless (@entry.user == current_user || current_user.member_entries.include?(@entry))
  end

    # Only allow a trusted parameter "white list" through.
    def entry_params
      params.fetch(:entry, {}).permit(:title, :description, :notes, :content, :tag_list)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = [] and return unless current_user
    owner_projects = Project.left_outer_joins(:users).where(owner_id: current_user.id).distinct(:project => :id)
    member_projects = Project.left_outer_joins(:users).where(:users => {id: current_user.id}).distinct(:project => :id)
    @projects = owner_projects.or(member_projects)
  end

  def show
    @project = Project.find(params[:id])
    @member_users = User.joins({:projects => :entries}).where(:users => {id: current_user.id}).uniq
    head :unauthorized and return unless (@project.owner == current_user || @member_users.include?(current_user))
  end

  def new
    head :unauthorized and return unless current_user
    @project = Project.new
    @entries = current_user.accessible_entries
    @users = User.all
  end

  def edit
    @project = Project.find(params[:id])
    @entries = current_user.accessible_entries
    @users = User.all
    head :unauthorized and return unless @project.owner == current_user
  end

  def create
    head :unauthorized and return unless current_user
    @project = Project.new(project_params.merge(owner_id: current_user.id))
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end
  
  def update
    @project = Project.find(params[:id])
    head :unauthorized and return unless @project.owner == current_user
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    head :unauthorized and return unless @project.user == current_user
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end
  
  private

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.fetch(:project, {}).permit(:title, :description, :entry_ids => [], :user_ids => [])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def landing_page
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @entries = Entry.where(user_id: current_user.id)
    member_entries = Entry.joins({:projects => :users}).where(:users => {id: current_user.id}).distinct(:entries => :id)
    @entries += member_entries
    @tags = @entries.map do |entry|
      entry.tags
    end
    @tags.flatten!.uniq!
  end
  
  def show
    @tag = params[:tag]
    @entries = Entry.where(user_id: current_user.id).tagged_with params[:tag]
    member_entries = Entry.joins({:projects => :users}).where(:users => {id: current_user.id}).distinct(:entries => :id).tagged_with @tag
    @entries += member_entries
    @entries.uniq!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<script>
  document.addEventListener("DOMContentLoaded", function() {
    window.onbeforeunload = function() { return true; };
    document.getElementsByTagName("form")[0].onsubmit = function(e) {
      window.onbeforeunload = null;
      return true;
    };
  });
</script>
<%= form_with model: entry, local: true do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title %>
  <%= form.text_field :title, size: 90 %>
  </br>
  <%= form.label :description %>
  <%= form.text_field :description, size: 90 %>
  </br>
  <div class="notes-and-content">
    <div class="notes">
      <%= form.label :notes %>
      <%= form.text_area :notes, cols: 20, rows: 20 %>
    </div>
    <div class="content">
      <%= form.label :content %>
      <%= form.text_area :content, cols: 60, rows: 20 %>
    </div>
  </div>
  <%= form.label :tag_list %>
  <%= form.text_field :tag_list, size: 50 %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <% unless @includes.blank? %>
    Includes: <%= @includes.join(', ') %>
    </br>
  <% end %>
  <% unless @excludes.blank? %>
    Excludes: <%= @excludes.join(', ') %>
  <% end %>
</h1>
  </br>
  <% @entries.each do |entry| %>
    <div class='entry'>
      <%= link_to entry.title, entry_path(entry), class: "title" %>
      <div class='entry_body'>
        <b>
          <%= simple_format entry.description %>
        </b>
        <div class='entry-content'>
          <%= simple_format entry.content %>
        </div>
        <b>Tags:</b>
        <% entry.tag_list.each do |tag| %>
          <%= link_to tag, tag_path(tag) %>
        <% end %>
        </br>
        <b>Owner:</b>
        <%= entry.user.email %>
        </br>
        </br>

        <b>Included In Projects:</b></br>
        <div class='indent'>
          <% entry.projects.each do |project| %>
            <%= link_to project.title, project %></br>
            <div class='indent'>
              <b>Members:</b></br>
              <% project.users.each do |user| %>
              <%= user.email %></br>
              <% end %>
              </br>
            </div>
          <% end %>
        </div>
        </br>

        <%= link_to 'Show', entry %> |
        <%= link_to 'Edit', edit_entry_path(entry) %> |
        <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </br>
      </br>
      </br>
    </div>
  <% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Return to Index', entries_path %></br></br>

<div class='entry'>
  <%= simple_format @entry.title, { class: 'title' }, { wrapper_tag: 'div' } %>
  <b><%= simple_format @entry.description %></b>
  <%= simple_format @entry.content, class: 'entry-content' %>
  <% unless @entry.notes.blank? %>
    <div class='entry-notes'>
      <%= simple_format @entry.notes %>
    </div>
  <% end %>
  <b>Tags:</b>
  <% @entry.tag_list.each do |tag| %>
    <%= link_to tag, tag_path(tag) %>
  <% end %>
  </br>
  </br>
  <b>Owner:</b>
  <%= @entry.user.email %>
  </br>
  </br>
  <b>Included In Projects:</b></br>
  <% @entry.projects.each do |project| %>
    <b><%= link_to project.title, project %></b></br>
    <div class='indent'>
      <b>Members:</b></br>
      <% project.users.each do |user| %>
      <%= user.email %></br>
      <% end %>
    </div>
  <% end %>
  </br>
  <%= link_to 'Edit', edit_entry_path(@entry) %> |
  <%= link_to 'Destroy', @entry, method: :delete, data: { confirm: 'Are you sure?' } %>
  </br>
  </br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taggr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p>
      <% unless controller_name == 'static' %>
        <%= link_to 'Back to search', landing_page_path %> |
      <% end %>
      <%= link_to 'New Entry', new_entry_path %> |
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<script>
  document.addEventListener("DOMContentLoaded", function() {
    window.onbeforeunload = function() { return true; };
    document.getElementsByTagName("form")[0].onsubmit = function(e) {
      window.onbeforeunload = null;
      return true;
    };
  });
</script>

<%= form_with model: project, local: true do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title %>
  <%= form.text_field :title, size: 90 %>
  </br>
  <%= form.label :description %>
  <%= form.text_area :description, cols: 60, rows: 10 %>
  </br>

  <div id='entries-area'>
    <input name="project[entry_ids][]" type="hidden">
    <%= form.label :entries %>
    <% @project.entries.each do |the_entry| %>
      <div class='entry-option'>
        <select name="project[entry_ids][]">
          <% @entries.each do |entry| %>
            <option value="<%= entry.id %>" <%= the_entry.title == entry.title ? 'selected' : nil %>><%= entry.title %></option>
          <% end %>
        </select>
        <button class="remove-entry-button" type="button">Remove This Entry</button>
      </div>
    <% end %>
  </div>
  <button id='add-entry-button' type="button">Add Entry</button>
  </br>

  <div id='users-area'>
    <input name="project[user_ids][]" type="hidden">
    <%= form.label :users %>
    <% @project.users.each do |the_user| %>
      <div class='user-option'>
        <select name="project[user_ids][]">
          <% @users.each do |user| %>
            <option value="<%= user.id %>" <%= the_user.email == user.email ? 'selected' : nil %>><%= user.email %></option>
          <% end %>
        </select>
        <button class="remove-user-button" type="button">Remove This User</button>
      </div>
    <% end %>
  </div>
  <button id='add-user-button' type="button">Add User</button>

  </br>

  <template id="entry-template">
    <div class='entry-option'>
      <select name="project[entry_ids][]">
        <% @entries.each do |entry| %>
          <option value="<%= entry.id %>"><%= entry.title %></option>
        <% end %>
      </select>
      <button class="remove-entry-button" type="button">Remove This Entry</button>
    </div>
  </template>

  <template id="user-template">
    <div class='user-option'>
      <select name="project[user_ids][]">
        <% @users.each do |user| %>
          <option value="<%= user.id %>"><%= user.email %></option>
        <% end %>
      </select>
      <button class="remove-user-button" type="button">Remove This User</button>
    </div>
  </template>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
</br>
<% @projects.each do |project| %>
  <%= simple_format project.title, { class: 'title' }, { wrapper_tag: 'div' } %>
  <%= simple_format project.description %>
  <b>Owner:</b>
  <%= project.owner.email %>
  </br>
  </br>
  <b>Members:</b></br>
  <div class='indent'>
  <% project.users.each do |user| %>
    <%= user.email %>
    </br>
  <% end %>
  </div>
  </br>
  <b>Entries:</b></br>
  <div class='indent'>
    <% project.entries.each do |entry| %>
      <%= link_to entry.title, entry %></br>
    <% end %>
    </br>
  </div>
  <%= link_to 'Show Project', project %>
  </br>
  </br>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Return to Index', projects_path %></br></br>

<div class='project'>
  <%= simple_format @project.title, { class: 'title' }, { wrapper_tag: 'div' } %>
  <%= simple_format @project.description %>
  <b>Owner:</b>
  <%= @project.owner.email %>
  </br>
  </br>
  <b>Members:</b></br>
  <div class='indent'>
  <% @project.users.each do |user| %>
    <%= user.email %>
    </br>
  <% end %>
  </div>
  </br>
  <b>Entries:</b></br>
  <div class='indent'>
    <% @project.entries.each do |entry| %>
      <%= link_to entry.title, entry %></br>
    <% end %>
    </br>
  </div>
  <%= link_to 'Edit Project', edit_project_path(@project) %>
</div>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag.name) %>
  </br>
<% end %>

app/views/tags/show.html.erb
<h1 class='show_tag_display'>
  Showing tag: <%= @tag %>
</h1>
<% @entries.each do |entry| %>
<div class='entry'>
  <%= simple_format entry.title, { class: 'entry-title' }, { wrapper_tag: 'div' } %>

    <div class='entry_body'>
      <b>
        <%= simple_format entry.description %>
      </b>
      <div class='entry-content'>
        <%= simple_format entry.content %>
      </div>
      <b>Tags:</b>
      <% entry.tag_list.each do |tag| %>
        <%= link_to tag, tag_path(tag) %>
      <% end %>
      </br>
      <%= link_to 'Show', entry %> |
      <%= link_to 'Edit', edit_entry_path(entry) %> |
      <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </br>
    </br>
  </div>
<% end %>